from typing import Protocol


class ILikeDm(Protocol):
    async def lock_post(self, *, post_id: int) -> bool: ...

    async def exists(self, *, user_id: int, post_id: int) -> bool: ...

    async def create(self, *, user_id: int, post_id: int) -> None: ...

    async def delete(self, *, user_id: int, post_id: int) -> None: ...
